#!/usr/bin/env bash
# This script configures an Ubuntu server to change home IP resolutions

cp /etc/hosts /tmp/new_hosts

sed -i 's/.*localhost.*/127.0.0.2 localhost/' /tmp/new_hosts
sed -i 's/.*facebook.com.*/8.8.8.8 ://facebook.com' /tmp/new_hosts

if ! grep -q "facebook.com" /tmp/new_hosts; then
    echo "8.8.8.8 facebook.com" >> /tmp/new_hosts
fi

cat /tmp/new_hosts > /etc/hosts
rm /tmp/new_hosts
