#!/usr/bin/env bash
# This script configures an Ubuntu server to change home IP resolutions

if grep -q "localhost" /etc/hosts; then
    sed -i 's/.*localhost.*/127.0.0.2 localhost/' /etc/hosts
else
    echo "127.0.0.2 localhost" >> /etc/hosts
fi

if grep -q "facebook.com" /etc/hosts; then
    sed -i 's/.*facebook.com.*/8.8.8.8 ://facebook.com' /etc/hosts
else
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
